# Generated by Django 3.0.6 on 2020-05-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C19Autoaval',
            fields=[
                ('pk_c19_autoaval', models.BigAutoField(primary_key=True, serialize=False)),
                ('nr_cpf', models.CharField(max_length=11)),
                ('dt_avaliacao', models.DateField(blank=True, null=True)),
                ('fl_febre', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_dorcabeca', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_secrecao', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_garganta', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_tosse', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_respirar', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_dorcorpo', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_diarreia', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_olfpaladar', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_14contato', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'c19_autoaval',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C19Cadastro',
            fields=[
                ('pk_c19_cadastro', models.BigAutoField(primary_key=True, serialize=False)),
                ('nr_cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('no_funcionario', models.CharField(blank=True, max_length=100, null=True)),
                ('fl_sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('dt_nascimento', models.DateField(blank=True, null=True)),
                ('nr_nit', models.CharField(blank=True, max_length=11, null=True)),
                ('nr_cbo', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('nr_cep', models.CharField(blank=True, max_length=8, null=True)),
                ('no_logradouro', models.CharField(blank=True, max_length=140, null=True)),
                ('sg_uf', models.CharField(blank=True, max_length=2, null=True)),
                ('nr_numero', models.CharField(blank=True, max_length=8, null=True)),
                ('no_bairro', models.CharField(blank=True, max_length=40, null=True)),
                ('no_cidade', models.CharField(blank=True, max_length=40, null=True)),
                ('nr_celular', models.CharField(blank=True, max_length=11, null=True)),
                ('no_email', models.CharField(blank=True, max_length=140, null=True)),
                ('cd_codemp', models.CharField(blank=True, max_length=5, null=True)),
                ('nr_matricula', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'c19_cadastro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C19Teste',
            fields=[
                ('pk_c19_teste', models.BigAutoField(primary_key=True, serialize=False)),
                ('dt_coleta', models.DateField(blank=True, null=True)),
                ('dt_resultado', models.DateField(blank=True, null=True)),
                ('dt_sintomas', models.DateField(blank=True, null=True)),
                ('fl_resultado', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_febre', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_dorcabeca', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_secrecao', models.CharField(blank=True, max_length=1, null=True)),
                ('nr_cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('fl_garganta', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_tosse', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_respirar', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_dorcorpo', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_diarreia', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_olfpaladar', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_14contato', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_diabetes', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_hipertensao', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_renal', models.CharField(blank=True, max_length=1, null=True)),
                ('fl_resgrave', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'c19_teste',
                'managed': True,
            },
        ),
    ]
