# Generated by Django 3.0.5 on 2020-05-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appc19', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='c19autoaval',
            name='dt_cancel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c19autoaval',
            name='dt_criado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c19autoaval',
            name='id_cancel',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='c19autoaval',
            name='id_criado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='c19cadastro',
            name='dt_cancel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c19cadastro',
            name='dt_criado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c19cadastro',
            name='id_cancel',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='c19cadastro',
            name='id_criado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='c19teste',
            name='dt_cancel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c19teste',
            name='dt_criado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c19teste',
            name='id_cancel',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='c19teste',
            name='id_criado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
    ]
